### ISSUE TITLE
Utilisation FormCreator

### ISSUE THREAD

**Issue by RaphaelVI** [InfotelGLPI/servicecatalog#2]
Bonjour,

Lorsque j'essaye de relier un formulaire FormCreator à une catégorie de ticket dans le Catalogue de Service, de cette manière : 
![image](https://user-images.githubusercontent.com/38419198/206594865-12b14ae4-24d2-4927-ba03-a78eabdafaa0.png)

Il n'apparait pas lorsque je choisi la catégorie dans le catalogue de service
J'ai aussi essayé de changer la valeur de "Mode d'assistance" dans l'onglet "Formulaires" de mon entité pour toutes les valeurs possibles, sans effet

Merci !

**Comment by tsmr** [comment]
Hello
In english, please.

Have you read informations on our wiki for fromcreator connection ?

**Comment by RaphaelVI** [comment]
No I had not !
But I found the answer on the [wiki](https://clientsglpi.infotel.com/fr/notices/noticepluginservicecatalog), thank you
